; =============================================================================
; SAGA DARK — +2 128K — Dragon Phase (Dark 3) as standalone minigame
; -----------------------------------------------------------------------------
; Dark 3 is a single-shot 25 536-byte program at ORG 0x9C40 with an offscreen
; buffer (title screen) at 0x8140-0x9C3F. Entry at 0x9C40 is `JP INICIO`
; (0x9F7E) which copies the buffer to screen, waits for key 0x1D, then CLS +
; init. Uses 48K BASIC ROM (CALL 0x0D6B = CLS, CALL 0x0556 = LOAD-BYTES via
; cassette tape — but on +2 the cassette is irrelevant; the relevant ROM
; calls are CLS and similar utility routines).
;
; The offscreen buffer at 0x8140-0x9C3F is NOT just a one-shot title bitmap:
; the gameplay engine reuses it as a sprite/tile source for sky/ground/dragon
; rendering, so the region must stay resident with its title-shaped contents
; throughout the minigame. The B+ on-demand pass that worked for the film does
; not apply here — see the user-memory entry "dragon-0x8140-is-sprite-source".
;
; Memory map (per docs/dark3-memory-map.md):
;   0x0000-0x3FFF  ROM (48K BASIC)
;   0x4000-0x57FF  Screen pixels
;   0x5800-0x5AFF  Screen attributes
;   0x5B00-0x5BFF  Bootstrap (this file)
;   0x5C00-0x813F  System vars + Dark 3 specific data tables
;   0x8140-0x9C3F  Offscreen title screen buffer (LDIR'd to 0x4000 by INICIO
;                  AND reused as sprite/tile source during gameplay)
;   0x9C40-0xFFFF  Dark 3 code + data + sprites + loader (25 536 B from .bin)
; =============================================================================

        DEVICE ZXSPECTRUM128

PORT_7FFD       EQU 0x7FFD
PORT_BORDER     EQU 0xFE
ENTRY           EQU 0x9C40       ; first byte of dark3.bin = JP INICIO (0x9F7E)
PILA            EQU 0x813D       ; SP per dark3.sna

; --- Slot mapping --------------------------------------------------------
        SLOT 1
        PAGE 5
        SLOT 2
        PAGE 2
        SLOT 3
        PAGE 0
        SLOT 1

; --- Pre-loaded RAM in banks 5+2 (0x4000-0x9C3F) -------------------------
; Was a single preload.bin extracted from dark3.sna (offset 27). Split
; (2026-05-12) into three logical pieces so the divergent fork can evolve
; each independently:
;   src/screen.bin           ← 0x4000-0x5AFF (6912 B) screen pixels + attrs
;   src/sysvars-data.asm     ← 0x5C00-0x813F (9536 B) sysvars + boot tables
;                              as editable DEFS+DEFB
;   src/offscreen-title.bin  ← 0x8140-0x9C3F (6912 B) offscreen title buffer
;                              ("TEO, THE DRAGON" image) LDIRed to 0x4000 by
;                              INICIO. Also a sprite/tile source during
;                              gameplay — must remain resident as-is.
        ORG 0x4000
        INCBIN "src/screen.bin"

        INCLUDE "src/sysvars-data.asm"

        ORG 0x8140
        INCBIN "src/offscreen-title.bin"

; --- IM 2 + master_im2 + PT3 helpers (bank 5 zero gap) -------------------
        INCLUDE "src/music/master_im2.asm"

; --- Bootstrap at 0x5B00 (overwrites the printer-buffer area) ------------
        ORG 0x5B00
boot_start:
        di
        xor a
        out (PORT_BORDER), a
        ld sp, PILA
        ld bc, PORT_7FFD
        ld a, 0x10                      ; 48K ROM in slot 0, bank 0 in slot 3
        out (c), a
        ; --- Music init: page bank 3 (player + module), INIT PT3, page bank 0 back.
        call music_init
        ; --- IM 2 install. Vector @ 0x7777 → master_im2 (in src/music/).
        ld a, 0x78
        ld i, a
        im 2
        ei
        jp ENTRY

; --- Bank 3: PT3 player + Mountain King module (paged in slot 3 only during
;     music_tick / music_init / music_pause). Same pattern as the film. ---
; The player hardcodes ORG 0xC000 internally; we honour that and the module
; INCBIN sits right after the player. The PT3 player INIT (via music_init in
; bank 5) is told to read the module at song_pt3_data, and reserves its
; ~600 B VARS area between code end and module start.
        SLOT 3
        PAGE 3
        ORG 0xC000

; MODULE encapsulation: the player exports START/INIT/PLAY/MUTE/MODADDR/...
; as global labels. Wrapping in `MODULE pt3` prefixes them all (pt3.START,
; pt3.INIT, …) so they don't collide with anything in dragon.asm. We call
; the player via absolute addresses 0xC003 (INIT) and 0xC005 (PLAY) so we
; don't need the label names — only the `ORG 0xC000` inside the include.
        MODULE pt3
        INCLUDE "src/music/pt3_play.asm"
        ENDMODULE

; Mountain King — generated by tools/pt3-compose-mountain-king.py.
; In the Hall of the Mountain King by Edvard Grieg (1875), public domain.
song_pt3_data:
        INCBIN "src/music/mountain-king.pt3"

; Victory theme — generated by tools/pt3-compose-victory.py. A major,
; ~117 BPM, fanfare + Grieg-motif-in-major + cadence. Loaded by
; music_init_victory from victory_handler; the player switches back to
; mountain-king when victory_handler returns to INICIO.
victory_pt3_data:
        INCBIN "src/music/victory.pt3"

; Restore bank 0 in slot 3 so SAVESNA records bank 0 as the slot 3 current.
        SLOT 3
        PAGE 0

; --- Dark 3 code — 0x9C40-0xFFFF, 25 536 B ------------------------------
; Spans bank 2 (0x9C40-0xBFFF) and bank 0 (0xC000-0xFFFF). Source is now
; LOCAL to this folder (src/) — divergent from the 48K reference. Future
; feature subversions (multi-language overlays, NIRVANA+ multicolour, AY,
; ZX0, …) land here without touching `original-48k/`.
        ORG ENTRY
        INCLUDE "src/dragon.asm"

; --- Save 128K snapshot --------------------------------------------------
        SAVESNA "saga-dragon-128k.sna", boot_start
