#!/usr/bin/env python3
"""
Split a Dark 3 (.sna) reference into the three pieces the +2 128K dragon
build now uses instead of a single 23 616 B preload.bin:

  - screen.bin           (0x4000-0x5AFF, 6912 B) screen pixels + attrs
  - sysvars-data.asm     (0x5C00-0x813F, 9536 B) sysvars + boot tables as
                         editable DEFS+DEFB. Non-zero data is gathered into
                         6 small islands (~462 B); the surrounding zero fill
                         becomes DEFS directives.
  - offscreen-title.bin  (0x8140-0x9C3F, 6912 B) offscreen "TEO, THE DRAGON"
                         title buffer that INICIO LDIRs to 0x4000.

The .sna's RAM image starts at file offset 27 (after the SNA header).

Usage:
  python3 tools/dragon-split-preload.py <dark3.sna> <out_dir>

Verifies the regenerated layout is byte-perfect against the source RAM
at 0x4000-0x9C3F before writing anything.
"""

import os
import sys

SNA_HEADER = 27
RAM_BASE = 0x4000
RAM_END = 0x9C40           # exclusive
SCREEN_END = 0x5B00        # exclusive (0x4000-0x5AFF)
BOOTSTRAP_END = 0x5C00     # exclusive (0x5B00-0x5BFF — all zeros, bootstrap will overlay)
SYSVARS_END = 0x8140       # exclusive (0x5C00-0x813F)
GAP_THRESHOLD = 8          # merge non-zero runs separated by <8 zero bytes


def find_islands(data: bytes) -> list[tuple[int, int]]:
    runs: list[tuple[int, int]] = []
    in_run = False
    start = 0
    gap = 0
    for i, b in enumerate(data):
        if b != 0:
            if not in_run:
                start = i
                in_run = True
            gap = 0
        else:
            if in_run:
                gap += 1
                if gap >= GAP_THRESHOLD:
                    # last non-zero was at (i - gap); exclusive end = (i - gap + 1)
                    runs.append((start, i - gap + 1))
                    in_run = False
                    gap = 0
    if in_run:
        runs.append((start, len(data)))
    return runs


def render_sysvars_asm(sysvars: bytes, base_addr: int) -> str:
    runs = find_islands(sysvars)
    total_nz = sum(e - s for s, e in runs)
    out: list[str] = []
    out.append('; -----------------------------------------------------------------------------')
    out.append('; Dragon Phase - sysvars + Dark 3 boot tables (0x5C00-0x813F).')
    out.append(';')
    out.append('; Replaces the sysvars region of preload.bin with an editable DEFS+DEFB layout.')
    out.append(f'; {len(sysvars)} B total: {len(runs)} islands of non-zero data (~{total_nz} B) embedded in zero fill.')
    out.append('; Byte-perfect against the dark3.sna RAM at 0x5C00-0x813F.')
    out.append(';')
    out.append('; Islands detected in dark3.sna at boot time:')
    for idx, (s, e) in enumerate(runs):
        addr_s = base_addr + s
        addr_e = base_addr + e - 1
        out.append(f';   - Island {idx+1}: 0x{addr_s:04X}-0x{addr_e:04X} ({e-s} B)')
    out.append(';')
    out.append('; Auto-generated by tools/dragon-split-preload.py - re-run the helper to refresh')
    out.append('; if the source .sna changes.')
    out.append('; -----------------------------------------------------------------------------')
    out.append('')
    out.append(f'        ORG 0x{base_addr:04X}')
    out.append('')
    cur = 0
    end_total = len(sysvars)
    for idx, (s, e) in enumerate(runs):
        if s > cur:
            fill = s - cur
            out.append(f'        DEFS 0x{fill:04X}, 0   ; 0x{base_addr+cur:04X}-0x{base_addr+s-1:04X} ({fill} B fill)')
        chunk = sysvars[s:e]
        addr = base_addr + s
        out.append('')
        out.append(f'; --- Island {idx+1}: 0x{addr:04X}-0x{addr+len(chunk)-1:04X} ({len(chunk)} B) ---')
        for line_off in range(0, len(chunk), 16):
            row = chunk[line_off:line_off+16]
            hexbytes = ', '.join(f'0x{b:02X}' for b in row)
            out.append(f'        DEFB {hexbytes}    ; 0x{addr+line_off:04X}')
        out.append('')
        cur = e
    if cur < end_total:
        fill = end_total - cur
        out.append(f'        DEFS 0x{fill:04X}, 0   ; 0x{base_addr+cur:04X}-0x{base_addr+end_total-1:04X} ({fill} B tail fill)')
    out.append('')
    return '\n'.join(out)


def reconstruct(sysvars: bytes, runs: list[tuple[int, int]]) -> bytes:
    """Re-build sysvars from the islands + zero fills to verify byte-perfectness."""
    rec = bytearray()
    cur = 0
    for s, e in runs:
        if s > cur:
            rec.extend(b'\x00' * (s - cur))
        rec.extend(sysvars[s:e])
        cur = e
    if cur < len(sysvars):
        rec.extend(b'\x00' * (len(sysvars) - cur))
    return bytes(rec)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    sna_path = sys.argv[1]
    out_dir = sys.argv[2]

    with open(sna_path, 'rb') as f:
        sna = f.read()
    ram = sna[SNA_HEADER:SNA_HEADER + (RAM_END - RAM_BASE)]
    if len(ram) != (RAM_END - RAM_BASE):
        print(f'error: source .sna RAM image is {len(ram)} B, expected {RAM_END - RAM_BASE}', file=sys.stderr)
        return 1

    screen = ram[0:SCREEN_END - RAM_BASE]
    bootstrap = ram[SCREEN_END - RAM_BASE:BOOTSTRAP_END - RAM_BASE]
    sysvars = ram[BOOTSTRAP_END - RAM_BASE:SYSVARS_END - RAM_BASE]
    offscreen = ram[SYSVARS_END - RAM_BASE:RAM_END - RAM_BASE]

    if any(b != 0 for b in bootstrap):
        print('warning: bootstrap region (0x5B00-0x5BFF) is not all zeros — bootstrap LDIR may corrupt data', file=sys.stderr)

    # Byte-perfect check on the sysvars round-trip before we write anything.
    runs = find_islands(sysvars)
    rec = reconstruct(sysvars, runs)
    if rec != sysvars:
        print('error: sysvars reconstruction mismatch — refusing to write', file=sys.stderr)
        return 1

    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, 'screen.bin'), 'wb') as f:
        f.write(screen)
    with open(os.path.join(out_dir, 'offscreen-title.bin'), 'wb') as f:
        f.write(offscreen)
    asm = render_sysvars_asm(sysvars, BOOTSTRAP_END)
    with open(os.path.join(out_dir, 'sysvars-data.asm'), 'w') as f:
        f.write(asm)

    print(f'wrote screen.bin            ({len(screen)} B)')
    print(f'wrote offscreen-title.bin   ({len(offscreen)} B)')
    print(f'wrote sysvars-data.asm      ({len(runs)} islands, total {sum(e-s for s,e in runs)} B of DEFB; rest DEFS)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
